services:
  mysql:
    image: mysql:8.0
    container_name: itgo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    networks:
      - my-network

  redis:
    image: redis:latest
    container_name: itgo-redis
    ports:
      - "6379:6379"
    networks:
      - my-network

  application:
    build:
      context: .
    container_name: itgo-application
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
